### ISSUE TITLE
Bugs on Diematic3qMQTT.py

### ISSUE THREAD

**Issue by Wrafal** [Benoit3/Diematic_to_MQTT#1]
buffer.update('targetTemp',floatValue(self.targetTemp));	buffer.update('returnTemp',floatValue(self.targetTemp));

instead of reading the return temperature, it kept giving the same temperature as the set point.

Very good job. Works great with a Sofath Caliane heat pump (of course I had to make some code changes).

P.S. maybe you know how to combine readings from 2 addresses into one topic. I am talking about the addresses 508 and 507 (burner starts for a gas furnace and cooling compressor starts for me.

**Comment by Benoit3** [comment]
Hello,
I thank you for the bug you've found. I just correct it and push it on github.
For your question, you've an example here for datetime :

https://github.com/Benoit3/Diematic_to_MQTT/blob/main/src/Diematic3Panel.py#L344

It is an attribute with setter and getter (I've prefixed it with "_") : 
https://github.com/Benoit3/Diematic_to_MQTT/blob/main/src/Diematic3Panel.py#L284
https://github.com/Benoit3/Diematic_to_MQTT/blob/main/src/Diematic3Panel.py#L288

One question:
Where did you find register table for your heat pump ? I know people which could be interested  in.

**Comment by Wrafal** [comment]
***@***.***


this is my direct e-mail address.


looking on the internet, I came across a forum and someone posted the
address of the registers for the dedetrich furnace there. I did an ass of
addresses from 1 to 880 and compared with the registers for the gas stove
and with the readings on the panel. I have diematic.4 I still miss it a bit
but somehow I can do it. when I have all the registers I will send you the
2nd version of the program ;-) especially for dedetrich / sofath heat pumps.


tell me if there would be a lot of changes in the program to use the
rs485usb (dev / ttyUSB0) adapter instead of the tcpip converter because it
takes up much less space.


give me your direct e-mail address and I will contact you as soon as I have
registers for heat pumps.



czw., 2 gru 2021, 19:53 użytkownik Benoit3 ***@***.***>
napisał:

**Comment by Wrafal** [comment]
can we make any direct contact. email would be the best. I would give you everything that I have managed to do to this day. then I have a few questions about your code. because I am trying to make changes to the code and the script does not start.

**Comment by Benoit3** [comment]
Hello,
email adresses are cleared by Github.I didn't receive your email.
If you have some question about the code, the best solution is to ask
them on a forum dedicated to  this kind of subject (
https://community.home-assistant.io/t/de-dietrich-diematic-modbus-to-mqtt-interface/363086
).
 I will try answer to them,  everybody will take advantage of the
discussion and somebody could propose interesting solutions.
If you want to share some modification of the  code (for discussion),
the best solution is to fork my code into your own Github space and to
modify it.

Regards,Benoit
