### ISSUE TITLE
Regulator ebv delta 23b

### ISSUE THREAD

**Issue by Enjoy-Combi** [Benoit3/Diematic_to_MQTT#13]
Dear Benoit,

Many thanks for sharing your work. I am not a specialist and I wonder if I can use you work with this regulator : ebv delta 23b
[0450000312_1750_BA_DELTA-_EbV_FR.pdf](https://github.com/Benoit3/Diematic_to_MQTT/files/13237584/0450000312_1750_BA_DELTA-_EbV_FR.pdf)
I went on the web and see no data regarding the communication protocol with this regulator. Probably have to consider the regulator you have.

Many thanks in advance for your return.

**Comment by Benoit3** [comment]
Hello,
I thank you for the interest you have in this solution.
But the likelihood this regulator works with Diematic_to_MQTT is very low. It's not a De Dietrich regulator, there is no ModBus connector...

Regards,
Benoit

**Comment by Enjoy-Combi** [comment]
Hi,

Many thanks for this clarification, a day I will think about buying De Dietrich one. Hopefully the one in operation will die soon and that will be the opportunity :-)
