### ISSUE TITLE
Utilisation sur DTG 1300-24 eco v130

### ISSUE THREAD

**Issue by romgere** [Benoit3/Diematic_to_MQTT#14]
Bonjour,

Je me permet d'ouvrir une issue, même si je crains de déjà connaître la réponse...

Depuis quelque jours je chercher à comprendre comment je pourrais connecter ma Chaudière gaz DTG 1300-24 eco v130 à une solution domotique. Après pas mal de temps à fouiller ce projet me semblais être le plus prometteur, mais je ne pense pas qu'il correspond à mon modèle de chaudière...

En effet si j'ai bien compris il est nécessaire d'avoir une interface de contrôle de type Diematic sur ma chaudière, qui si je comprend bien n'a rien à voir avec "Easymatic" (j'ai tellement déterré/vu de post de forum que je commence à être perdu)...

Qui dit chaudière équipée avec Diematic, dit un panneau de control "éléctronique" sur la chaudière comme celui en page d'accueil de ce repo ?

Celui de ma chaudière ressemble à ça : 
![image](https://github.com/Benoit3/Diematic_to_MQTT/assets/13900970/8a7a950a-1528-431b-8754-01e5f3ace56a)
Et ma chaudière est piloté par un thermostat identique à celui en page d'accueil : 
![image](https://github.com/Benoit3/Diematic_to_MQTT/assets/13900970/1c439628-8a39-43c3-b645-6eef591def76)

Quelqu'un peut me confirmer que ce n'est pas du Diematic et que donc, je ne peux pas piloter ma chaudière avec Diematic_to_MQTT 🤔 ?

Je me permet également de citer https://github.com/Benoit3/Diematic_to_MQTT/issues/11 où il est dit que "la chaudière implémente un protocole ModBus largement modifié" mais celà ne semble pas empêcher @famdeg d'utiliser le projet.

Enfin, je suis tombé sur des (très) vieux posts de forum (notamment [celui là](https://www.domotique-fibaro.fr/topic/11578-easymatic-de-dietrich-city-124-bic-ii/?page=2)) où il est question du protocole "[Easymatic](https://sigrok.org/wiki/Protocol_decoder:Easymatic)" avec des tentatives d'implementation avait été faites, mais apparement sans jamais aboutir... (Je présume que le protocol "Easymatic" est celui que ma chaudière utilise pour communiquer avec mon thermostat ?)

Voilà, voilà, sans grand espoir je jète une bouteille à la mer ici 😅 si une âme charitable à des réponses à m'offrir ce serait super !

Un grand merci d'avance !

**Comment by Benoit3** [comment]
Bonjour,
je ne comprends pas, je pensai avoir répondu un peu plus tot, mais je ne trouve pas trace de la réponse et l'issue est toujours ouverte ...

Les interfaces de communication avec les regulateurs Diematic sont très peu documentées et il est difficile de dire si une régulation implémente une interface/protocole  ou pas. Par contre on ne voit pas comment ou pourrait faire tourner les boutons rotatifs de votre régulateur avec des commandes modbus et donc cela risque effectivement de ne pas être compatible.

La seule solution qui reste est de s'interfacer au niveau du lien easymatic. Les docs que vous avez mentionnées sont un très bon début. Mais c'est à terminer. La solution pourrait être de remplacer la commande à distance par un modèle maison (arduino ou autre) pilotable par ethernet.
Par contre il faut des compétences en électronique, logiciel , un peu de matériel (oscilloscope) et malheureusement pas mal de temps ...

Cordialement,
Benoit

**Comment by romgere** [comment]
Merci @Benoit3 pour cette réponse, c'est bien ce que j'avais en tête... Je vais attendre mon RDV annuel de revision pour demander à mon Chauffagiste si il n'y a pas moyen d'y mettre une commande Diematic (Je sais que le modèle de ma chaudière est compatible).

Sinon, effectivement, j'essaierai de me plonger dans le protocol EasyMatic les competences logiciels & électronique ne seront pas un problème, le temps (et l'oscilloscope) le seront surement un peu plus 😅 

Merci pour ta réponse et bravo pour ce beau projet, qui je l'espère, me permettra un jour d'ajouter un peu de domotique chez moi.
