### ISSUE TITLE
Compatibility issue with Paho-MQTT 2.0

### ISSUE THREAD

**Issue by rofiq65** [Benoit3/Diematic_to_MQTT#18]
Hi
After upgrading Paho-MQTT to version 2.0 there is a “callback_api_version” issue without possibility to launch the diematic service. So to make it compatible with paho-mqtt 2.0, there is a quick fix by just changing in Diematic32MQTT.py Line 322

client = mqtt.Client()
 
to

client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1)

Merci
Rofiq

**Comment by Benoit3** [comment]
Hi,
thank you for the quick return.
To keep compatibility with Paho MQTT v1.xx (and not request users to upgrade it now) , I propose [following modification ready on the branch](https://github.com/Benoit3/Diematic_to_MQTT/commit/d2a9a1859d4fa4d0fee402cd31e18106d0624ab0)

I've tested it OK with paho mqtt v1.61. Can you test it on your system (with Paho MQTT V2.0 if I understand well) ?

Log in DEBUG mode shows the Paho version detected.
Regards,
Benoit

**Comment by Benoit3** [comment]
Correction commit replaced [by this one](https://github.com/Benoit3/Diematic_to_MQTT/commit/03bbb00b661e8bed2f141bff32c9cb0a87e32915)
