### ISSUE TITLE
MasterReadError ... Frame too short  -  Diematic Delta

### ISSUE THREAD

**Issue by gomerust** [Benoit3/Diematic_to_MQTT#2]
Salut Benoit,

I've got a Problem with connecting my Boiler. I know you espacially wrote it for the diematic 3. ive got a diematic delta from 1997.

i read in somewhere in the openhab forums that the delta only uses Single Master Mode and sleeps the other 5 Seconds.

Since i am not a Developer i wanted to ask you, if you had the time and nerves to help me get infos out of my chaudiere. in dont really need to set things, it would just help to get infos and help using less oil.

2022-09-30 20:19:35,985 - DDModbus - WARNING - WRITE_MULTIPLE_REGISTERS frame too short
2022-09-30 20:19:39,169 - Diematic3Panel - INFO - ModBus Master Slave Synchro OK
2022-09-30 20:19:41,671 - DDModbus - WARNING - No answer to masterReadAnalog
2022-09-30 20:19:41,672 - Diematic3Panel - WARNING - ModBus Master Slave Synchro Error
2022-09-30 20:19:46,012 - DDModbus - WARNING - WRITE_MULTIPLE_REGISTERS frame too short
2022-09-30 20:19:48,678 - Diematic3Panel - INFO - ModBus Master Slave Synchro OK
2022-09-30 20:19:51,181 - DDModbus - WARNING - No answer to masterReadAnalog

Thank You

Thomas

**Comment by Benoit3** [comment]
Hello,

the MQTT interface is dedicated to Diematic3 and not compatible with Diematic Delta.
The MQTT interface use mainly as a modbus master during the slave mode period of the boiler.
The Diematic Delta is always in slave mode.
You can find information [here](https://www.domotique-fibaro.fr/topic/5677-de-dietrich-diematic-isystem/?page=6&tab=comments#comment-156190), maybe unfortunately in french (that's not an issue for me :-) )
The are some example but no ready to use solution.

Benoit

**Comment by gomerust** [comment]
Hi Benoît,I didn’t expect such a fast answer. Thank you, will try something. Unfortunately I am not good at programming. Bash is the most advanced “programming language” I can use 😉I can read code. Maybe I can Frankenstein something together.Have good time Et salutAm 30.09.2022 um 23:33 schrieb Benoit3 ***@***.***>:﻿
Hello,
the MQTT interface is dedicated to Diematic3 and not compatible with Diematic Delta.
The MQTT interface use mainly as a modbus master during the slave mode period of the boiler.
The Diematic Delta is always in slave mode.
You can find information here, maybe unfortunately in french (that's not an issue for me :-) )
The are some example but no ready to use solution.
Benoit

**Comment by Benoit3** [comment]
You can find hereafter a translation of a post on the fibaro french forum (https://www.domotique-fibaro.fr/topic/5677-de-dietrich-diematic-isystem/?page=6&tab=comments#comment-156190), thanks to "Briseis"

The essential difference between Diematic3 and Diematic Delta is that in the Delta, DD does not use a bi-master modbus protocol, that is to say, for 5 seconds, the boiler is master and interrogates the slaves while it has envy, then for 5 seconds it becomes a slave and possibly responds to a master who has taken control of the bus during this period.

For the Delta, it is a dual "Master / Absence" protocol: The boiler is master for 5 seconds, then will release the bus during the other seconds, but no longer listens to what is happening on the bus. She cannot therefore answer a possible question from another master. To confirm this, if we look at the 'ADM483' chip which transforms the RS485 link into TTL, we see that the PIN RE (active at 0) is at 1 when the boiler releases the bus. So she can't "hear anything".

On the other hand, what is interesting is that during its master period, the boiler interrogates a particular slave, at the address 0x32 (50) and that if this slave responds, it will modify these parameters. The operation is as follows:

The boiler sends a "Multiple Write Register" command containing the 123 registers of its "first page of parameters". Then if slave 0x32 responds to it, then it asks for the same 123 registers (Multiple Read Register"), and if the slave responds, having possibly modified 1 or more registers, then the boiler updates this first page of registers, then goes to page 2 (registers from 124 to 246), then to page 3 (from 247 to 369).

=> It's possible program this slave 0x32 to receive and modify / send back the parameters of the boiler.

**Comment by Benoit3** [comment]
hello ,
I've add a list of changes on dev branch which should allow to receive some info from a Diematic Delta. To use it set regulator to DiematicDelta in conf file, and log in DEBUG mode in logging.conf. Have  look in log.out

**Comment by matiou11** [comment]
Thanks! I ordered an Rs485 to ethernet box and will try to make it work with my Diematic Delta. I will let you know how it goes.

**Comment by gomerust** [comment]
Hi, i already tried the dev branch. My problem is, I can see packets/frames with Modbus data, but I have no clue how to read them. 🤯Regards and thank you for your helpAm 13.12.2022 um 13:08 schrieb matiou11 ***@***.***>:﻿
Thanks! I ordered an Rs485 to ethernet box and will try to make it work with my Diematic Delta. I will let you know how it goes.

**Comment by gomerust** [comment]
Matiou, I can share my dump if it helps analyzing.Von meinem iPhone gesendetAm 13.12.2022 um 13:08 schrieb matiou11 ***@***.***>:﻿
Thanks! I ordered an Rs485 to ethernet box and will try to make it work with my Diematic Delta. I will let you know how it goes.

**Comment by Benoit3** [comment]
No additionnal post during one year on this topic.
