### ISSUE TITLE
Unable to retrieve A or B zone target temp without a connected room thermostat "Control Panel"

### ISSUE THREAD

**Issue by giteki** [Benoit3/Diematic_to_MQTT#4]
Salut Benoît,

Without a room thermostat aka "Control Panel" connected to the boiler (i.e. no information retrieved on 18 DDREGISTER) the following conditionnal test in Diematic3Panel.py code prevents retrieving proper information regarding target A temp  (same for B with the 27 DDREGISTER) : 

```
		self.zoneATemp=self.float10(self.registers[DDREGISTER.TEMP_AMB_A]);
		if ( self.zoneATemp is not None):
			modeA=self.registers[DDREGISTER.MODE_A]& 0x2F;
```

A quick and dirty solution is to provide a switch from the configuration file, enforcing the test to True if needed

```
         self.zoneATemp=self.float10(self.registers[DDREGISTER.TEMP_AMB_A]);
         if ( self.zoneATemp is not None) or self.ForceAMode:
             self.logger.info(f"zoneATemp is :'{self.zoneATemp}'");
             self.logger.info(f"ForceAMode is :'{self.ForceAMode}'");
```
Here for example ForceAMode is set to True in the configuration file and provided to the function (code not ready to be published).

**Comment by Benoit3** [comment]
Bonjour,
je n'ai sais pas si vous avez reçu une notification, mais normalement
vos remarques sont prises en compte.Si jamais vous avez le temps de
vérifier, n'hésitez pas.
Il ne faut pas oublier d'ajouter les paramètres adéquats dans le
fichier de config.
Cordialement,Benoit Sandré

**Comment by giteki** [comment]
Bonsoir Benoit,
Merci pour votre message. Réponse tardive car je n'ai pas vraiment eu le temps de me re-pencher sur la question (j'avais fait quelque modification en dur à l'époque - cf l'issue - ce qui m'a permis de faire fonctionner votre code sans problème sur mon installation) . Je regarderai la nouvelle version et vous tiendrai au courant si problème. Si je faisais évoluer pour capter les autres valeurs (température fumée etc.) via des paramètres de config je verserai sur le git. 
Encore merci du partage à la communauté et d'être aussi réactif dans les corrections
Bien cordialement,
